<?
/*##################################################################################################
# Описание действия скрипта: 
##################################################################################################*/
$page_title="Услуги брикетирования";
$page_keywords="забрикетировать стружку, забрикетировать брикет, брикетировочные линии, услуги брикетирования, брикетирование";
$page_description="Наша компания оказывает услуги по брикетированию металлической стружки для ферросплавного производства";
$page_robots="index,follow";
include '../../system_files/settings.php';
include '../../system_files/core.php';
include '../../page_elements/head.php';
?>
<section class="breadcrumbs-custom"><div class="breadcrumbs-custom__aside bg-image context-dark" style="background-image:url(/images/system/template_img/ferroalloy_briquetting_title_img.jpg)"><div class="container"><h4 class="breadcrumbs-custom__title">Услуги по брикетированию для ферросплавного производства</h4></div></div><div class="d-none d-lg-block d-sm-block breadcrumbs-custom__main bg-gray-light"><div class="container"><ul class="breadcrumbs-custom__path"><li><a href="/">Главная</a></li><li><a href="/briquetting-press">Брикетировочные пресса</a></li><li class="active">Услуги брикетирования стружки</li><li><a href="/briquette_production">Производство и реализация брикетов</a></li></ul></div></div></section>
<div class="container-fluid text-center pb-4 pt-2" style="background: #f2a4a4;"><h3 class="font-weight-bold">Внимание! Данная услуга теперь не предоставляется!</h3><div class="row mt-3"><div class="col-0 col-sm-1 col-lg-2"></div><div class="col-12 col-sm-10 col-lg-8"><p class="text-justify p_text">Вместо этого мы можем предложить Вам пресса для брикетирования металлической стружки и другого сырья. Ознакомиться с продукцией можно по этой ссылке: <a href="https://steelcom-jdh.ru/products">steelcom-jdh.ru</a></p></div></div></div>
<section class="section section-sm pt-5 bg-white"><div class="container"><div class="row row-50 justify-content-md-center justify-content-lg-start"><div class="col-12">
<div class="box-inset-1"><h2 class="text-center">Брикеты как альтернатива</h2><p class="p_text">На протяжении всей своей деятельности компания LLC «SteelCom» оказывает услуги по брикетированию металлической стружки</p><div class="image-custom-1"><img src="/images/system/template_img/briket-press.png" alt="Разработка программных продуктов" width="550" height="341"></div><p class="p_text">На данный момент компания приступила к производству новой линейки промышленного оборудования, а именно, брикетировочные пресса для прессования брикетов различных категорий. Брикеты в качестве альтернативы и дополнения к классическому сырью в металлургии, так же решают проблему вторичной переработки отходов и получения дешёвого сырья для плавки с заданным химическим составом. Пресс поможет Вашему бизнесу производить брикеты различных категорий. Брикеты как компоненты шихты эффективно заменяют шлакообразующие материалы, металлолом, раскисляющие и легирующие добавки в сталелитейном производстве. Применяются для восстановления железа, получения CO при обжиге в печах, получения извести для металлургического передела. С недавнего времени мы стали оказывать услуги по брикетированию различного стороннего сырья.</p></div></div><div class="col-12"><div class="box-inset-1"><h4>Используя собственные производственные мощности оказываем услуги предприятиям по переработке материалов.</h4><ul class="list-marked list_inset" style="font-size:initial"><li>Услуги по брикетированию отходов ферросплавных производств</li><li>Услуги по брикетированию отсева флюсующих компонентов БАК</li><li>Услуги по брикетированию Пылевидных отходов аспирационных установок электрофильтра и скруббера конвертерного производства</li><li>Услуги по брикетированию отходов сталеплавильных производств.</li><li>Услуги по брикетированию собственной стружки предприятий с полным циклом производства от литья до обработки для наиболее близкой химии исходного расплава</li></ul><br><h5>Условия и цена переработки оговариваются в каждом конкретном случае отдельно</h5></div></div></div></div></section><section class="section section-sm bg-white"><div class="container"><div class="row justify-content-md-center justify-content-lg-start"><div class="col-md-12 col-lg-12 text-center"><div class="metall_button metall_button-sm align-center button-zoom metal_btn_size"><div class="pt-2" style="max-width:none"><a href="/feedback"><h3 style="font-size:25px">Напишите нам</h3></a></div></div></div></div></div></section>
<?
include '../../page_elements/foot.php';
?>